# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import maas_chat_gateway_pb2 as protos_dot_maas__chat__gateway__pb2


class MaaSChatGatewayServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Chat = channel.unary_unary(
                '/mmu.maas.chat.MaaSChatGatewayService/Chat',
                request_serializer=protos_dot_maas__chat__gateway__pb2.KuaiYiChatCompletionRequest.SerializeToString,
                response_deserializer=protos_dot_maas__chat__gateway__pb2.KuaiYiChatCompletionResponse.FromString,
                )
        self.ChatBiStream = channel.stream_stream(
                '/mmu.maas.chat.MaaSChatGatewayService/ChatBiStream',
                request_serializer=protos_dot_maas__chat__gateway__pb2.KuaiYiChatCompletionRequest.SerializeToString,
                response_deserializer=protos_dot_maas__chat__gateway__pb2.KuaiYiChatCompletionResponse.FromString,
                )
        self.ChatServerStream = channel.unary_stream(
                '/mmu.maas.chat.MaaSChatGatewayService/ChatServerStream',
                request_serializer=protos_dot_maas__chat__gateway__pb2.KuaiYiChatCompletionRequest.SerializeToString,
                response_deserializer=protos_dot_maas__chat__gateway__pb2.KuaiYiChatCompletionResponse.FromString,
                )


class MaaSChatGatewayServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Chat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChatBiStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChatServerStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MaaSChatGatewayServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Chat': grpc.unary_unary_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=protos_dot_maas__chat__gateway__pb2.KuaiYiChatCompletionRequest.FromString,
                    response_serializer=protos_dot_maas__chat__gateway__pb2.KuaiYiChatCompletionResponse.SerializeToString,
            ),
            'ChatBiStream': grpc.stream_stream_rpc_method_handler(
                    servicer.ChatBiStream,
                    request_deserializer=protos_dot_maas__chat__gateway__pb2.KuaiYiChatCompletionRequest.FromString,
                    response_serializer=protos_dot_maas__chat__gateway__pb2.KuaiYiChatCompletionResponse.SerializeToString,
            ),
            'ChatServerStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ChatServerStream,
                    request_deserializer=protos_dot_maas__chat__gateway__pb2.KuaiYiChatCompletionRequest.FromString,
                    response_serializer=protos_dot_maas__chat__gateway__pb2.KuaiYiChatCompletionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mmu.maas.chat.MaaSChatGatewayService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MaaSChatGatewayService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mmu.maas.chat.MaaSChatGatewayService/Chat',
            protos_dot_maas__chat__gateway__pb2.KuaiYiChatCompletionRequest.SerializeToString,
            protos_dot_maas__chat__gateway__pb2.KuaiYiChatCompletionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ChatBiStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/mmu.maas.chat.MaaSChatGatewayService/ChatBiStream',
            protos_dot_maas__chat__gateway__pb2.KuaiYiChatCompletionRequest.SerializeToString,
            protos_dot_maas__chat__gateway__pb2.KuaiYiChatCompletionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ChatServerStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/mmu.maas.chat.MaaSChatGatewayService/ChatServerStream',
            protos_dot_maas__chat__gateway__pb2.KuaiYiChatCompletionRequest.SerializeToString,
            protos_dot_maas__chat__gateway__pb2.KuaiYiChatCompletionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
